### ISSUE TITLE
Can't get it to work in Kodi Jarvis 16.1

### ISSUE THREAD

**Issue by ronniehd** [anxdpanic/context.youtube.download#2]
Kodi is installed on Windows 10 x64 and I have installed latest version of this YouTube add-on: http://forum.kodi.tv/showthread.php?tid=267160
I have youtube-dl add-on setup. 
When I press "c" to open Context Menu in Video Title or while video is playing I don't see any Download option or anything that is related to youtube-dl.

**Comment by anxdpanic** [comment]
Have you also installed this repository and add-on? 

https://github.com/anxdpanic/context.youtube.download#installation

If so, can you post a kodi.log
